apiVersion: apps/V1
kind: Deployment
metadata:
     name: deployment-api-conversion
spec:
     replicas: 10
     selector: 
     matchLabels:
          app: api-conversion
     template:
          metadata:
               labels:
               app: api-conversion
               spec:
                    Containers:
                         image: rayanperes/api-conversion:v1
                         ports:
                              - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
     name: api-conversion-service
spec:
     selector:
          app: api-conversion
     ports:
          - port: 80
          nodePort: 30000
     type: NodePort